### ISSUE TITLE
reverse to original?

### ISSUE THREAD

**Issue by jlgouveia** [nicolaisi/tancolor#11]
is it possible to revert the effect to the original for an mouse out?

**Comment by nicolaisi** [comment]
For the current version no, but if this is somewhat important, I could probably implement this. Maybe add a function to reload the picture.

**Comment by jlgouveia** [comment]
That would be awesome !

:)

Jose Luis Gouveia
Digital Producer
Web Manager at The Lisbon School of Design

me@joseluisgouveia.com
+351 96 506 03 32
+351 210 803 174
skype: jlgouveia

**Comment by nicolaisi** [comment]
Hi, I added an extra function called "load". I updated this on the example as well. Released this on the 0.1.3 version.

Now you can reload your image as follow:

```
 $("#myImage").tancolor({load: 'images/obama.jpg'});
```
